- app/assets/stylesheets/products.scss
- app/views/products/index.html.haml
> top-page-view4

- app/controllers/purchase_controller.rb
- app/views/purchase/done.html.haml
- app/views/purchase/index.html.haml
> image_display_feature_addition

- app/views/products/show.html.haml
- app/views/purchase/confirm.html.haml
- config/routes.rb
> route_change

- app/views/mypages/card.html.haml
- app/views/mypages/identification.html.haml
- app/views/mypages/logout.html.haml
- app/views/mypages/profile.html.haml
- app/views/mypages/show.html.haml
- app/views/products/_header.html.haml
- config/routes.rb
> My page link adjustment

- Capfile
- Gemfile
- Gemfile.lock
- app/assets/javascripts/sell.js
- app/assets/stylesheets/new.scss
- app/controllers/signup_controller.rb
- app/views/products/new.html.haml
- capistrano-rails-consoleをインストール
- 商品出品画面の画像プレビュー機能を実装
> Install capistrano rails console

- Gemfile
- Gemfile.lock
- app/views/products/_header.html.haml
- config/breadcrumbs.rb
> Breadcrumb introduction

- app/assets/stylesheets/products/_show.scss
- app/controllers/products_controller.rb
- app/views/products/show.html.haml
- config/routes.rb
> 商品削除機能の実装#2

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/breadcrumbs.scss
- app/views/layouts/_breadcrumbs.html.haml
- app/views/mypages/card.html.haml
- app/views/mypages/identification.html.haml
- app/views/mypages/logout.html.haml
- app/views/mypages/profile.html.haml
- app/views/mypages/show.html.haml
- config/breadcrumbs.rb
> Breadcrumb function implementation

- app/views/mypages/card.html.haml
- app/views/mypages/identification.html.haml
- app/views/mypages/logout.html.haml
- app/views/mypages/profile.html.haml
- app/views/mypages/show.html.haml
> listing_button_edit

- app/controllers/signup_controller.rb
- app/views/devise/sessions/new.html.haml
- app/views/signup/creditcard.html.haml
- app/views/signup/registration.html.haml
> Add recaptcha#2

- app/assets/javascripts/category_select_box.js
- app/assets/javascripts/sell.js
- app/controllers/products_controller.rb
- app/views/products/new.html.haml
> Sell function improvement

- app/models/address.rb
- app/views/purchase/confirm.html.haml
- app/views/purchase/done.html.haml
> Purchase function edit

- app/assets/javascripts/product_new_price.js
- app/assets/stylesheets/products/_show.scss
- app/views/products/new.html.haml
- app/views/products/show.html.haml
商品出品画面に価格を入力した際、販売利益を表示できるようにする
> Add price-preview on add-product-page

- app/assets/javascripts/product_new_price.js
- app/assets/stylesheets/products/_show.scss
- app/views/products/edit.html.haml
> Update price preview on product edit#2

- app/assets/javascripts/mypage.js
- app/assets/stylesheets/mypages/mypages.scss
- app/views/mypages/show.html.haml
> Implementation ajax to my page

- app/assets/javascripts/sell.js
- app/views/layouts/application.html.haml
> Drag and drop feature

- app/assets/javascripts/pulldown.js
- app/assets/stylesheets/products/products.scss
- app/views/products/_header.html.haml
> Pulldown menu 2 1

- app/controllers/products_controller.rb
#What
- トップページにブランド一覧を表示する為のサーバーサイド側を作成
> Top page brand

- app/assets/stylesheets/products/_show.scss
- app/assets/stylesheets/products/products.scss
- app/controllers/mypages_controller.rb
- app/controllers/purchase_controller.rb
- app/views/products/show.html.haml
- config/routes.rb
> Bug fix 12

- app/views/devise/sessions/new.html.haml
- app/views/products/show.html.haml
- 商品詳細画面の"変更する"ボタンにクラス名を追加
- ログインページのFB&Googleによるログインボタンの文言を修正
> Minor update
